[package]
name = "stest"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
getopts = "0.2.24"
walkdir = "2.5.0"

[profiles.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
